# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eszti és Ádi kalandozásai
description: > # this means to ignore newlines until "baseurl:"
  Ezt a honlapot Ádi készítette Esztinek a 26. szülinapjára a közös útjaikon készült képek visszanézegetésére.
baseurl: ""   # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
port: 4000
host: "0.0.0.0"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "galleries"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
